# DataSource Config

# 该配置的名称是固定的，不可以改变，否则将不能自动加载到数据源中
spring:
  datasource:
    url: jdbc:mysql://ip:port/qimeishop?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      pool-name: DatebookHikariBuilding
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  servlet:
    multipart:
      ##上传文件单个文件的大小
      max-file-size: 50MB
      ##上传文件单次请求的文件的总大小
      max-request-size: 300MB

  # redis
  redis:
    host: ip
    port: port
    timeout: 30000
    password: password
    database: 11
    jedis:
      pool:
        minIdle: 1
        maxIdle: 10
        maxWait: 3
        maxActive: 8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    return-instance-for-empty-row: true