server:
  port: 8990


admin:
  token:
    timeout: 300
  password:
    md5:
      key: 893d4a24ff3a4fbd9c644b3fff8fa0a0

user:
  token:
    timeout: 300


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

wx:
  url: https://api.weixin.qq.com/sns/jscode2session
  appId: wx2f27b5d170401608
  secret: 04ec05a2381008ddbd87f4316d7ef3c5